"""破砕(Cell Fracture)・剛体設定・ベイクなど、形状に依存しない共通ロジック。

generators/gen_destruction_scene.py の fracture_and_setup_physics /
bake_simulation_to_keyframes をパラメータ化して移植したもの。
"""

import math
import random

import bpy


def ensure_cell_fracture():
    """同梱(vendor)のCell Fractureアドオンが未登録なら登録する。"""
    if hasattr(bpy.types, "OBJECT_OT_add_fracture_cell_objects"):
        return
    from .vendor.object_fracture_cell import register as _register_cell_fracture

    _register_cell_fracture()


def set_active(obj):
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj


def find_or_create_ground(target_obj):
    """is_destruction_groundタグ付きオブジェクトを探す。無ければ対象の footprint に
    合わせた地面を新規生成してタグを付ける(任意の既存メッシュを直接分解する経路向け)。
    """
    for obj in bpy.context.scene.objects:
        if obj.get("is_destruction_ground"):
            return obj

    bbox_world = [target_obj.matrix_world @ v.co for v in target_obj.data.vertices] if target_obj.data.vertices else []
    if bbox_world:
        min_x = min(v.x for v in bbox_world)
        max_x = max(v.x for v in bbox_world)
        min_y = min(v.y for v in bbox_world)
        max_y = max(v.y for v in bbox_world)
        min_z = min(v.z for v in bbox_world)
        center_x = (min_x + max_x) * 0.5
        center_y = (min_y + max_y) * 0.5
        half_w = max((max_x - min_x) * 1.6, 3.0)
        half_d = max((max_y - min_y) * 1.6, 3.0)
        ground_top_z = min_z
    else:
        center_x = center_y = 0.0
        half_w = half_d = 5.0
        ground_top_z = 0.0

    thickness = 0.10
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(center_x, center_y, ground_top_z - thickness * 0.5))
    ground = bpy.context.active_object
    ground.name = "Destruction_Ground"
    ground.scale = (half_w, half_d, thickness)
    bpy.ops.object.transform_apply(scale=True)
    ground["is_destruction_ground"] = True
    return ground


def fracture_object(target_obj, shard_count, shard_noise, seed_val):
    """対象メッシュをCell Fractureで破砕し、非キネマティックの固定剛体ネットワークを作る。

    破断閾値(breaking_threshold)はここでは設定しない(unbreakable相当の大きな値の
    まま)。Impact/Naturalどちらのcollapseトリガーになるかで欲しい分布が違うため、
    実際の値は destruction.trigger_collapse 側で割り当てる。
    """
    ensure_cell_fracture()
    target_name = target_obj.name
    set_active(target_obj)

    pre_names = {o.name for o in bpy.context.scene.objects}

    random.seed(seed_val)
    bpy.ops.object.add_fracture_cell_objects(
        source_limit=int(shard_count),
        source_noise=float(shard_noise),
        margin=0.0,
        material_index=1,
        use_smooth_faces=False,
        use_sharp_edges=True,
        use_remove_original=True,
    )

    # 破砕で新しく生成されたオブジェクト名を特定
    new_names = [o.name for o in bpy.context.scene.objects if o.name not in pre_names]
    if not new_names:
        new_names = [o.name for o in bpy.context.scene.objects if "cell" in o.name.lower()]

    # 元オブジェクトが残存している場合は確実に削除
    if target_name in bpy.data.objects:
        old_obj = bpy.data.objects.get(target_name)
        if old_obj:
            bpy.data.objects.remove(old_obj, do_unlink=True)

    # 生存しているオブジェクト参照のみを名前から再取得（死にポインタ回避）
    shards = []
    for name in new_names:
        obj = bpy.data.objects.get(name)
        if obj and obj.name != target_name:
            shards.append(obj)

    if not shards:
        raise RuntimeError("No fracture shards were generated by Cell Fracture.")

    for s in shards:
        if not s.rigid_body:
            try:
                s.rigid_body_create(type="ACTIVE")
            except Exception:
                bpy.context.view_layer.objects.active = s
                bpy.ops.rigidbody.object_add(type="ACTIVE")
        if s.rigid_body:
            s.rigid_body.collision_shape = "CONVEX_HULL"
            s.rigid_body.mass = 4.5
            s.rigid_body.friction = 0.60
            s.rigid_body.restitution = 0.40
            s.rigid_body.linear_damping = 0.01
            s.rigid_body.angular_damping = 0.01

    bpy.ops.object.select_all(action="DESELECT")
    for s in shards:
        s.select_set(True)
    bpy.context.view_layer.objects.active = shards[0]
    bpy.ops.rigidbody.connect(con_type="FIXED", connection_pattern="CHAIN_DISTANCE")

    # トリガー(destruction.trigger_collapse)が呼ばれるまでは壊れないよう、
    # いったん非常に高い閾値にしておく。
    for o in _iter_constraint_objects(shards):
        if o.rigid_body_constraint:
            o.rigid_body_constraint.use_breaking = True
            o.rigid_body_constraint.breaking_threshold = 1_000_000.0

    for s in shards:
        s["destruction_shard"] = True

    return shards


def _iter_constraint_objects(shards):
    shard_names = {s.name for s in shards}
    for obj in bpy.data.objects:
        con = obj.rigid_body_constraint
        if not con or con.object1 is None or con.object2 is None:
            continue
        if con.object1.name in shard_names or con.object2.name in shard_names:
            yield obj


def apply_kinematic_freeze(shards, freeze_until_frame):
    """Impact用: 衝突が起きるフレームまでは静止(kinematic)させ、その直後に解放する。"""
    for s in shards:
        s.rigid_body.kinematic = True
        s.keyframe_insert(data_path="rigid_body.kinematic", frame=1)
        s.keyframe_insert(data_path="rigid_body.kinematic", frame=freeze_until_frame)
        s.rigid_body.kinematic = False
        s.keyframe_insert(data_path="rigid_body.kinematic", frame=freeze_until_frame + 1)


def set_uniform_breaking_threshold(shards, threshold):
    """Impact用: 全接合部を同一の破断閾値にする(衝撃波で一気に弾け飛ぶ見た目)。"""
    for obj in _iter_constraint_objects(shards):
        obj.rigid_body_constraint.use_breaking = True
        obj.rigid_body_constraint.breaking_threshold = float(threshold)


def randomize_breaking_thresholds(shards, threshold_min, threshold_max):
    """Natural用: 接合部ごとに破断閾値をランダム化し、崩れる時間差(段階的な崩落)を作る。"""
    lo, hi = float(threshold_min), float(threshold_max)
    if lo > hi:
        lo, hi = hi, lo
    for obj in _iter_constraint_objects(shards):
        obj.rigid_body_constraint.use_breaking = True
        obj.rigid_body_constraint.breaking_threshold = random.uniform(lo, hi)


def bake_simulation_to_keyframes(shards, ball=None, total_frames=100, time_scale=0.5):
    """物理演算をフレームごとに手動で進め、純粋なLocRotキーフレームとして焼き込む。

    bpy.ops.*.bake_all() 系はGUIのモーダル操作でバックグラウンド実行だと
    最初の数フレームしか進まないことがある(ProcVFXのMantaflowデバッグで判明した罠と
    同種)。scene.frame_set()での手動ステップならGUI操作時と同じ経路で確実に進む。
    """
    scene = bpy.context.scene
    if scene.rigidbody_world:
        scene.rigidbody_world.point_cache.frame_start = 1
        scene.rigidbody_world.point_cache.frame_end = total_frames
        scene.rigidbody_world.time_scale = float(time_scale)

    valid_shards = [s for s in shards if s.name in bpy.data.objects]

    baked_matrices = {s: [] for s in valid_shards}
    deps = bpy.context.evaluated_depsgraph_get()
    for f in range(1, total_frames + 1):
        scene.frame_set(f)
        deps.update()
        for s in valid_shards:
            eval_s = s.evaluated_get(deps)
            baked_matrices[s].append((f, eval_s.matrix_world.copy()))

    for s in valid_shards:
        if s.rigid_body:
            s.rigid_body.enabled = False
    if scene.rigidbody_world:
        scene.rigidbody_world.enabled = False

    for s in valid_shards:
        if s.animation_data:
            s.animation_data_clear()
        for f, mat in baked_matrices[s]:
            loc, rot, _sca = mat.decompose()
            s.location = loc
            s.rotation_euler = rot.to_euler()
            s.keyframe_insert(data_path="location", frame=f)
            s.keyframe_insert(data_path="rotation_euler", frame=f)

    for o in list(bpy.data.objects):
        if o.rigid_body_constraint or "Shockwave" in o.name:
            bpy.data.objects.remove(o, do_unlink=True)

    for obj in valid_shards + ([ball] if ball else []):
        if obj.animation_data:
            obj.animation_data.use_nla = False
            for track in list(obj.animation_data.nla_tracks):
                obj.animation_data.nla_tracks.remove(track)

    scene.frame_set(1)
    scene.frame_current = 1


def create_cannonball_material():
    mat = bpy.data.materials.new(name="Mat_Destruction_CannonBall")
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = (0.12, 0.12, 0.14, 1.0)
        bsdf.inputs["Metallic"].default_value = 0.92
        bsdf.inputs["Roughness"].default_value = 0.28
    return mat


def ensure_ground_passive_body(ground_obj):
    set_active(ground_obj)
    if not ground_obj.rigid_body:
        bpy.ops.rigidbody.object_add(type="PASSIVE")
    ground_obj.rigid_body.collision_shape = "BOX"
    ground_obj.rigid_body.friction = 0.85
    ground_obj.rigid_body.restitution = 0.15


def spawn_cannonball_and_shockwave(
    hit_pos, seed_val, ball_size, angle_h, angle_v, shock_power, impact_frame
):
    """砲弾(キネマティック軌道)+衝撃波フォースフィールドを生成する(Impact用)。"""
    random.seed(seed_val)
    cannon_mat = create_cannonball_material()

    rad_h = math.radians(angle_h)
    rad_v = math.radians(angle_v)
    dir_x = math.sin(rad_h) * math.cos(rad_v)
    dir_y = -math.cos(rad_h) * math.cos(rad_v)
    dir_z = -math.sin(rad_v)

    dist = 9.0
    hx, hy, hz = hit_pos
    start_pt = (hx - dir_x * dist, hy - dir_y * dist, hz - dir_z * dist)
    end_pt = (hx + dir_x * dist, hy + dir_y * dist, hz + dir_z * dist)

    bpy.ops.mesh.primitive_uv_sphere_add(radius=ball_size, location=start_pt)
    ball = bpy.context.active_object
    ball.name = "Destruction_CannonBall"
    bpy.ops.object.shade_smooth()
    ball.data.materials.append(cannon_mat)

    set_active(ball)
    if not ball.rigid_body:
        bpy.ops.rigidbody.object_add(type="PASSIVE")
    ball.rigid_body.collision_shape = "SPHERE"
    ball.rigid_body.kinematic = True

    near_hit = (hx - dir_x * 0.25, hy - dir_y * 0.25, hz - dir_z * 0.25)
    through_hit = (hx + dir_x * 0.50, hy + dir_y * 0.50, hz + dir_z * 0.50)
    mid_pt = (hx + dir_x * 3.5, hy + dir_y * 3.5, hz + dir_z * 3.5)

    for frame, loc in (
        (1, start_pt),
        (impact_frame, near_hit),
        (impact_frame + 3, through_hit),
        (impact_frame + 13, mid_pt),
        (impact_frame + 68, end_pt),
    ):
        ball.location = loc
        ball.keyframe_insert(data_path="location", frame=frame)

    size_factor = (ball_size / 0.50) ** 1.5
    shock_strength = float(shock_power) * size_factor

    bpy.ops.object.effector_add(type="FORCE", location=hit_pos)
    force = bpy.context.active_object
    force.name = "Destruction_Shockwave"
    force.field.shape = "POINT"
    for frame, strength in (
        (1, 0.0),
        (impact_frame, 0.0),
        (impact_frame + 1, shock_strength),
        (impact_frame + 3, shock_strength * 0.4),
        (impact_frame + 6, 0.0),
    ):
        force.field.strength = strength
        force.keyframe_insert(data_path="field.strength", frame=frame)

    return ball
